name: "name-webapp"
repo: "joomeco/name-webapp"
baseBranch: "main"

dev:
  baseUrl: "https://dev.xn--ame-6ma.es"

services:
  - repo: "joomeco/ms-name-restaurants"
  - repo: "joomeco/ms-name-orders"
  - repo: "joomeco/ms-name-users"
  - repo: "joomeco/ms-name-notifications"
  - repo: "joomeco/ms-name-payments"

qa:
  needsReview: true
  shadow: true
  testDataPrefix: "ñame"

report:
  onFailure: "github-issue"
